#!/bin/bash

#set -eo pipefail
[[ "$TRACE" ]] && set -x

: ${CLOUDBREAK_ADDRESS:=https://cloudbreak-api.sequenceiq.com/}
: ${IDENTITY_ADDRESS:=https://identity.sequenceiq.com}

cb_shell() {
    : ${SEQUENCEIQ_USER:? required}
    : ${SEQUENCEIQ_PASSWORD:? required}
    
    export CLOUDBREAK_ADDRESS IDENTITY_ADDRESS SEQUENCEIQ_USER SEQUENCEIQ_PASSWORD

    # we shouldnt pass any --xxx parameter, but 1 paam is required 
    # otherwise only the usage is printed and cb-shell terminates
    java -jar /cloudbreak-shell.jar --sequenceiq.user=SEQUENCEIQ_USER "$@"
}

check_custom_jar() {
    if [[ "$CLOUDBREAK_CUSTOM_JAR_URL" ]]; then
        curl -Lko /cloudbreak-shell.jar  "$CLOUDBREAK_CUSTOM_JAR_URL"
    fi
}

main() {
    check_custom_jar
    cb_shell "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
